name: Tests
 
on: ['push', 'pull_request']
 
jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Setup MySQL
        run: mysql -h 127.0.0.1 -P ${{ job.services.mysql.ports['3306'] }} -uroot -e 'CREATE DATABASE IF NOT EXISTS testing;'

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
 
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate

      - name: Tests
        run: ./vendor/bin/pest --coverage-clover coverage.xml
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}